-- Execute este arquivo no SQL Editor do Supabase
create table if not exists public.progresso_modulos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  modulo_id integer not null check (modulo_id between 1 and 7),
  concluido boolean not null default false,
  concluido_em timestamptz,
  atualizado_em timestamptz not null default now(),
  unique (user_id, modulo_id)
);

alter table public.progresso_modulos enable row level security;

drop policy if exists "Usuário lê o próprio progresso" on public.progresso_modulos;
create policy "Usuário lê o próprio progresso" on public.progresso_modulos for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Usuário insere o próprio progresso" on public.progresso_modulos;
create policy "Usuário insere o próprio progresso" on public.progresso_modulos for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Usuário atualiza o próprio progresso" on public.progresso_modulos;
create policy "Usuário atualiza o próprio progresso" on public.progresso_modulos for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
